version: '3.8'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
  backend:
    build: ./backend/
    depends_on:
      - db
    env_file: .env
    volumes:
      - static:/static
      - media:/media
  frontend:
    env_file: .env
    container_name: foodgram-front
    build: ./frontend
    volumes:
      - ./frontend/:/app/result_build/
      - static:/static
      - media:/media
    ports:
      - "3000:8000"
  nginx:
    build: ./infra/
    depends_on:
      - backend
    env_file: .env
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "8000:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/static/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - media:/media
      - static:/static
